### ISSUE TITLE
0.3.1: problem with building m2r2 from git repo

### ISSUE THREAD

**Issue by kloczek** [CrossNox/m2r2#38]
sdist tar ball does not contain `docs/`directory so I've been trying to use tagged tar ball to build new as rpm package but it fails
```console
+ /usr/bin/python3 setup.py build '--executable=/usr/bin/python3 -s'
Traceback (most recent call last):
  File "setup.py", line 14, in <module>
    from m2r2 import parse_from_file
  File "/home/tkloczko/rpmbuild/BUILD/m2r2-0.3.1/m2r2.py", line 19, in <module>
    __version__ = get_distribution("m2r2").version
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 466, in get_distribution
    dist = get_provider(dist)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 342, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 886, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 772, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'm2r2' distribution was not found and is required by the application
error: Bad exit status from /var/tmp/rpm-tmp.2yI2j1 (%build)
```
I see first time ever such effect.
May I ask for some hint/help?

**Comment by CrossNox** [comment]
Seems related to #22
Can you provide more info on your env?

**Comment by kloczek** [comment]
Python 3.8.12, pytest 6.2.5.
If you need more details please let me know (I'm not sure shat more I should provide in this case).

**Comment by kloczek** [comment]
Closing.
I'm no longer using setupftools to build modules and pep517 based build is working
```console
+ /usr/bin/python3 -sBm build -w --no-isolation
* Getting dependencies for wheel...
running egg_info
creating m2r2.egg-info
writing m2r2.egg-info/PKG-INFO
writing dependency_links to m2r2.egg-info/dependency_links.txt
writing entry points to m2r2.egg-info/entry_points.txt
writing requirements to m2r2.egg-info/requires.txt
writing top-level names to m2r2.egg-info/top_level.txt
writing manifest file 'm2r2.egg-info/SOURCES.txt'
reading manifest file 'm2r2.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching '__pycache__' found under directory '*'
warning: no previously-included files matching '*.py[co]' found under directory '*'
adding license file 'LICENSE'
writing manifest file 'm2r2.egg-info/SOURCES.txt'
* Building wheel...
running bdist_wheel
running build
running build_py
creating build
creating build/lib
copying m2r2.py -> build/lib
running egg_info
writing m2r2.egg-info/PKG-INFO
writing dependency_links to m2r2.egg-info/dependency_links.txt
writing entry points to m2r2.egg-info/entry_points.txt
writing requirements to m2r2.egg-info/requires.txt
writing top-level names to m2r2.egg-info/top_level.txt
reading manifest file 'm2r2.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching '__pycache__' found under directory '*'
warning: no previously-included files matching '*.py[co]' found under directory '*'
adding license file 'LICENSE'
writing manifest file 'm2r2.egg-info/SOURCES.txt'
installing to build/bdist.linux-x86_64/wheel
running install
running install_lib
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/wheel
copying build/lib/m2r2.py -> build/bdist.linux-x86_64/wheel
running install_egg_info
Copying m2r2.egg-info to build/bdist.linux-x86_64/wheel/m2r2-0.3.2-py3.8.egg-info
running install_scripts
adding license file "LICENSE" (matched pattern "LICEN[CS]E*")
creating build/bdist.linux-x86_64/wheel/m2r2-0.3.2.dist-info/WHEEL
creating '/home/tkloczko/rpmbuild/BUILD/m2r2-0.3.2/dist/tmp1hhnstjd/m2r2-0.3.2-py3-none-any.whl' and adding 'build/bdist.linux-x86_64/wheel' to it
adding 'm2r2.py'
adding 'm2r2-0.3.2.dist-info/LICENSE'
adding 'm2r2-0.3.2.dist-info/METADATA'
adding 'm2r2-0.3.2.dist-info/WHEEL'
adding 'm2r2-0.3.2.dist-info/entry_points.txt'
adding 'm2r2-0.3.2.dist-info/top_level.txt'
adding 'm2r2-0.3.2.dist-info/RECORD'
removing build/bdist.linux-x86_64/wheel
Successfully built m2r2-0.3.2-py3-none-any.whl
```
