### ISSUE TITLE
m2r2 fatal error due to extension crash

### ISSUE THREAD

**Issue by sistia01** [CrossNox/m2r2#48]
Hello! 

Thank you for updating this tool! I added m2r2 to my extensions list in my project ([here](https://github.com/sistia01/Giotto/tree/suite/docs)) but when I built the website via the readthedocs host it caused a fatal crash error:

**ModuleNotFoundError: No module named 'm2r2'** -- see below for more information on the error. 

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/giottoteam-giotto/envs/suite/lib/python3.7/site-packages/sphinx/cmd/build.py", line 279, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "/home/docs/checkouts/readthedocs.org/user_builds/giottoteam-giotto/envs/suite/lib/python3.7/site-packages/sphinx/application.py", line 245, in __init__
    self.setup_extension(extension)
  File "/home/docs/checkouts/readthedocs.org/user_builds/giottoteam-giotto/envs/suite/lib/python3.7/site-packages/sphinx/application.py", line 402, in setup_extension
    self.registry.load_extension(self, extname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/giottoteam-giotto/envs/suite/lib/python3.7/site-packages/sphinx/registry.py", line 421, in load_extension
    err) from err
sphinx.errors.ExtensionError: Could not import extension m2r2 (exception: No module named 'm2r2')

Extension error:
Could not import extension m2r2 (exception: No module named 'm2r2')

Any help with this would be appreciated!

**Comment by CrossNox** [comment]
Hi @sistia01, perhaps you should add it to your `requirements.txt`? I mean, [here](https://github.com/sistia01/Giotto/blob/suite/docs/requirements.txt).

**Comment by CrossNox** [comment]
@sistia01 were you able to solve this?

**Comment by sistia01** [comment]
Hi @CrossNox!

My apologies for the late reply, yes! Thank you very much or the help. I added m2r2 to the requirements.txt file and the website was able to be built.
